# Generated by Django 2.2.28 on 2023-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jvcee_vbb4'),
    ]

    operations = [
        migrations.AddField(
            model_name='jvcee',
            name='ghtt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
